version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - crocs-bridge-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - crocs-bridge-network

networks:
  crocs-bridge-network:
    driver: bridge