version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    container_name: zookeeper-server
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - crocs-bridge-network
    
  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka-server
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - crocs-bridge-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=crocs_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - crocs-bridge-network

  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - crocs-bridge-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - crocs-bridge-network

networks:
  crocs-bridge-network:
    driver: bridge